shop_app/urls.py
from django.urls import path
from . import views
app_name = "shop"

urlpatterns = [
    path('',views.index,name='index'),
    path('signin',views.signin,name="signin"),
    path('profile',views.profile,name="profile"),
    path('cart',views.cart,name="cart"),
    path('signup',views.signup,name="signup"),
    path('logout',views.logout,name="logout"),
    path("profile_update/<int:user_id>",views.profile_update,name="profile_update"),
    
    
]

shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop_app.urls')),
]

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

shop_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Items(models.Model):
    name = models.CharField(max_length=20)
    price = models.IntegerField()
    img = models.ImageField(upload_to='pics')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'items'



class Info(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to='pics',default='profile_default.jpg',blank=True)
    address = models.CharField(max_length=30)
    position = models.CharField(max_length=30)
    phone_number = models.IntegerField()
    DOB = models.DateField()

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Profiles'

shop_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Info
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Info
        exclude = ['user']
        widgets = {
            'address':forms.TextInput(attrs={'class':'form-control'}),
            'position':forms.TextInput(attrs={'class':'form-control'}),
            'phone_number':forms.TextInput(attrs={'class':'form-control'}),
            'DOB':forms.DateInput(attrs={'class':'form-control'}),
        }

shop_app/views.py
from django.shortcuts import render,redirect
from .models import Items,Info
from django.contrib.auth.models import User,auth
from .forms import ProfileForm
# Create your views here.
def index(request):
    items = Items.objects.all()
    user = request.user
    
    context = {'items':items,'user':user}
    return render(request,'index.html',context)

def signup(request):
    if request.method == 'POST':
        firstname = request.POST['fname']
        
        lastname = request.POST['lname']
        username = request.POST['uname']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        user = User.objects.create_user(first_name=firstname,last_name=lastname,username=username,email=email,password=password1)
        user.save()
        return redirect("/")
    else:

        return render(request,'signup.html')

def profile(request):
    profiles = Info.objects.all()
    context = {'profiles':profiles}
    return render(request,'profile.html',context)








def profile_update(request,user_id):
    profile = Info.objects.get(id=user_id)
    if request.method == 'POST':
        form = ProfileForm(request.POST,request.FILES,instance=profile)
        if form.is_valid():
            form.save()
            return redirect("shop:profile")
        else:
            return redirect("profile_update")

    else:
        form = ProfileForm(instance=profile)
        context = {'form':form,'profile':profile}
        return render(request,'update_profile.html',context)

def cart(request):
    return render(request,'cart.html')

def signin(request):
    if request.method == 'POST':
        uname = request.POST['uname']
        password = request.POST['password']

        user = auth.authenticate(username=uname,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect("/")
        else:
            print("Not valid")
            return redirect("shop:signin")
        
    else:
        return render(request,'signin.html')

def logout(request):
    auth.logout(request)
    return redirect("/")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<body>
    {% include 'header.html' %}
    {% block content %}
    {% endblock %}
    <script src="{% static '/js/scripts.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="display-4 text-center">Your items in cart</h1>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row justify-content-center text-center">
            <div class="col-4">
                <h1><small>Product</small></h1>
            </div>
            <div class="col-4">
                <h1><small>Price</small><h1>
            </div>
            <div class="col-4">
                <h1><small>Quantity</small></h1>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row items_in_cart justify-content-center text-center">

        </div>
    </div>
    <div class="container mt-4">
        <div class="row justify-content-center ">
            <div class="col-4 text-center bg-primary rounded-lg p-1" style="cursor: pointer;">
                <a href="{% url 'shop:index' %}" class="checkout text-white" style="text-decoration: none;" >Check Out</a>
            </div>
        </div>
    </div>
    
{% endblock %}

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Shopping</title>
    
    <link rel="icon" href="{% static '/images/icon.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">

    <style>
        *{
            font-family: 'Nunito', sans-serif;
        }
        .fa{
            font-size: 25px;
        }
        a{
            text-decoration: none;
        }
        *{
            font-family: 'Nunito', sans-serif;
        }
        
        .fa{
            font-size: 25px;
        }
        a{
            text-decoration: none;
        }
    </style>
</head>

templates/header.html
{% load static %}

<nav class="navbar navbar-expand-sm bg-light">
    <a href="#" class="navbar-brand">
        <img src="{% static '/images/logo.png' %}" alt="" class="img-fluid" style="max-width: 3em;">
    </a>
    <div class="list">
        <ul  class="navbar-nav">
            
            <li class="nav-item">
                <a href="{% url 'shop:index' %}" class="nav-link pl-4">Home</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link pl-4">About</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'shop:signup' %}" class="nav-link pl-4">Sign Up</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a href="{% url 'shop:logout' %}" class="nav-link pl-4">Logout</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'shop:profile' %}" class="nav-link pl-4">Profile</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{% url 'shop:signin' %}" class="nav-link pl-4">Sign In</a>
            </li>
            
            {% endif %}
            <li class="nav-item">
                <a href="{% url 'shop:cart' %}" class="nav-link pl-4 "><i class="fa fa-shopping-cart"></i>
                    <span style="padding:1px;background-color: rgb(222, 250, 98);border-radius: 5px;" class="cart_increase">0</span>
                </a>
            </li>
        </ul>
    </div>
    
</nav>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1 class="display-4 text-center">Items You Can Buy</h1>
    </div>
    <div class="container mt-4">
        <div class="row justify-content-center ">

            {% for item in items %}
            <div class="col-sm-3 shadow-sm items"  style="margin-bottom: 3em;">
                <div class="col-12">
                    <img src="{{item.img.url}}" alt="" class="img-fluid image">
                </div>
                <div class="col-12">
                    <h2 class="price"><small>${{item.price}}</small></h2>
                    <p class="name">{{item.name}}</p>
                    <button type="button" id="cart" class="btn btn-success w-60 add-cart" style="margin:0 auto;display:block;margin-bottom: 1em;;">Add to cart</button>
                </div>
            </div>
            {% endfor %}




            




        </div>
    </div>

    <div class="container-fluid bg-dark text-white">
        <div class="row justify-content-center"style="padding-top:4em;padding-bottom:2em;">
            <div class="col-4 text-center">
                <h1 style="color:orange;">Contacts</h1>
                <p>9841256884</p>
                <p>1245897896</p>
                <p>1457895656</p>
            </div>
            <div class="col-4 text-center">
                <h1 style="color:orange;">Services</h1>
                <p>Web Development</p>
                <p>App Development</p>
                <p>Domain Services</p>
            </div>
            <div class="col-4 text-center">
                <h1 style="color:orange;">Address</h1>
                <p>Washington DC</p>
                <p>USA</p>
            </div>
        </div>
    </div>

    <hr style="margin:0;padding:0;">
    <div class="container-fluid bg-dark">
        <div class="row">
            <div class="col-12 text-center mb-4">
                <p style="color:white;">&copy;  binayshrestha798@gmail.com</p>
                
            </div>
        </div>
    </div>


    
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container-fluid">
        
        {% for profile in profiles %}
            {% if user.is_authenticated %}
                {% if user.username == profile.user.username %}
        <div class="row justify-content-center">
            <div class="col-sm-8 bg-white profile">
                <div class="row shadow-lg">
                    <div class="col-sm-4">
                        {% if profile.thumbnail %}
                            <img src="{{profile.thumbnail.url}}" class="img-fluid  img-thumbnail m-4" alt="Image">
                        {% else %}
                        <img src="{% static '/images/profile_default.jpg' %}" class="img-fluid  img-thumbnail m-4" alt="Image">
                        {% endif %}
                        <a href="{% url 'shop:profile_update' profile.id %}">Edit Profile</a>
                    </div>
                    <div class="col-sm-8 " style="padding:1em 0 2em 8em;">
                        <h6><small class="font-weight-bold text-secondary">Hello everyone!!! I am</small></h6>
                        
                        
                        <h1 class="display-4">{{user.username|title}}</h1>
                        {% if profile.position %}
                        <p>{{profile.position}}</p>
                        {% else %}
                        <p>Profile</p>
                        {% endif %}
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sapiente 
                            ipsam quis explicabo praesentium molestias, molestiae quod inventore dolor 
                            fuga veritatis id saepe aliquam qui facilis laborum modi enim impedit
                             nostrum consectetur eveniet ducimus amet dolorum! Dolor nam quis ducimus?</p>
                        {% if profile.DOB %}
                        <i class='fa fa-calendar' style='font-size:24px;color:gray;'><span style="margin-left: 2em;">{{profile.DOB}}</span></i><br>
                        {% endif %}

                        {% if profile.DOB %}
                        <i class="fa fa-phone" style="color:gray;"><span style="margin-left: 2em;">{{profile.phone_number}}</span></i><br>
                        {% endif %}

                        {% if profile.DOB %}
                        <i class="fa fa-envelope"style="color:gray"><span style="margin-left: 2em;"></span>{{profile.user.email}}</i><br>
                        {% endif %}
                        
                        {% if profile.DOB %}
                        <i class="fa fa-home" style="color:gray"><span style="margin-left: 2em;">{{profile.address}}</span></i><br>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
                {% else %}
                
                {% endif %}
                
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

templates/signin.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-3 bg-light mt-4 shadow-lg rounded">
                <h1 class="text-center mb-4"><small>Login</small></h1>

                <form action="{% url 'shop:signin' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="uname" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" name="password" placeholder="Password">
                    </div>
                    <div class="form-group text-center">
                        <button class="btn btn-primary ">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-4 bg-white mt-4 rounded shadow-lg" >
                <div class="col-12">
                    <h1 class="text-center p-4"><small >Sign Up</small></h1>
                </div>
                <div class="col-12">
                    <form action="{% url 'shop:signup' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" name="fname" placeholder="First Name">
                            
                        </div>
                        
                        <div class="form-group">
                            <input type="text" class="form-control" name="lname" placeholder="Last Name">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="uname" placeholder="Username">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" name="email" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="password1" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="password2" placeholder="Confirm Password">
                        </div>
                        <div class="text-center mb-4">
                            <button type="submit" class="btn btn-primary w-50" >Submit</button>
                        </div>
                    </form>
                </div>
                
            </div>
        </div>
    </div>

{% endblock %}

templates/update_profile.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-6 shadow-lg p-4 rounded-lg">
                <h1 style="text-align:center">Update Profile</h1>
                <form action="{% url 'shop:profile_update' profile.id %}"method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
    
{%  endblock %}